### ISSUE TITLE
Issues with Android Back Button Crashing App (pictureInPicture)

### ISSUE THREAD

**Issue by jake-newsom** [jepiqueau/capacitor-video-player#66]
We're having issues in a few spots trying to use this plugin on Android 11.

1) Sometimes tapping the video and then tapping the close icon works, however sometimes it crashes the app and gives this error: 
`
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xxxxx.xxxxx, PID: 10011
    java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.next(ArrayList.java:860)
        at com.jeep.plugin.capacitor.capacitorvideoplayer.Notifications.NotificationCenter.postNotification(NotificationCenter.java:55)
        at com.jeep.plugin.capacitor.capacitorvideoplayer.FullscreenExoPlayerFragment.playerExit(FullscreenExoPlayerFragment.java:290)
        at com.jeep.plugin.capacitor.capacitorvideoplayer.FullscreenExoPlayerFragment.access$1100(FullscreenExoPlayerFragment.java:68)
        at com.jeep.plugin.capacitor.capacitorvideoplayer.FullscreenExoPlayerFragment$3$2.onClick(FullscreenExoPlayerFragment.java:243)
        at android.view.View.performClick(View.java:8160)
        at android.view.View.performClickInternal(View.java:8137)
        at android.view.View.access$3700(View.java:888)
        at android.view.View$PerformClick.run(View.java:30236)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8633)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)`

2) Pressing the hardware back button on android is crashing the app with the following error
`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xxxx.xxxxxx, PID: 11939
    java.lang.IllegalStateException: enterPictureInPictureMode: Current activity does not support picture-in-picture.
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2393)
        at android.os.Parcel.createException(Parcel.java:2369)
        at android.os.Parcel.readException(Parcel.java:2352)
        at android.os.Parcel.readException(Parcel.java:2294)
        at android.app.IActivityTaskManager$Stub$Proxy.enterPictureInPictureMode(IActivityTaskManager.java:7099)
        at android.app.Activity.enterPictureInPictureMode(Activity.java:2902)
        at com.jeep.plugin.capacitor.capacitorvideoplayer.FullscreenExoPlayerFragment.pictureInPictureMode(FullscreenExoPlayerFragment.java:308)
        at com.jeep.plugin.capacitor.capacitorvideoplayer.FullscreenExoPlayerFragment.backPressed(FullscreenExoPlayerFragment.java:275)
        at com.jeep.plugin.capacitor.capacitorvideoplayer.FullscreenExoPlayerFragment.access$600(FullscreenExoPlayerFragment.java:68)
        at com.jeep.plugin.capacitor.capacitorvideoplayer.FullscreenExoPlayerFragment$3$1.onKey(FullscreenExoPlayerFragment.java:208)
        at android.view.View.dispatchKeyEvent(View.java:15046)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1981)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
        at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:901)
        at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1947)
        at android.app.Activity.dispatchKeyEvent(Activity.java:4142)
        at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:122)
        at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
        at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:140)
        at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:569)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3054)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:756)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:7365)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7191)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6595)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6786)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6626)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6843)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6599)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6626)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6599)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6819)
        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:7007)
        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3624)
        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:3163)
        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:3154)
        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3601)
        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loop(Looper.java:206)
        at android.app.ActivityThread.main(ActivityThread.java:8633)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.wm.ActivityTaskManagerService.ensureValidPictureInPictureActivityParamsLocked(ActivityTaskManagerService.java:5204)
        at com.android.server.wm.ActivityTaskManagerService.enterPictureInPictureMode(ActivityTaskManagerService.java:5081)
        at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:3370)
        at android.os.Binder.execTransactInternal(Binder.java:1190)
        at android.os.Binder.execTransact(Binder.java:1159)`

but I see no way to just disable picture in picture in the documentation

We've set up these methods in our Vue code:
`

    async playVideo() {
      await this.addListenersToPlayerPlugin();

      await this.videoPlayer.initPlayer({
        url: this.personalizedVideoUrl,
        playerId: "fullscreen",
        mode: "fullscreen",
        componentTag: "div",
      });
    },
    
    async addListenersToPlayerPlugin(): Promise<void> {
      document.addEventListener('jeepCapVideoPlayerPlay', this.playerPlay, false);
      document.addEventListener('jeepCapVideoPlayerPause', this.playerPause, false);
      document.addEventListener('jeepCapVideoPlayerEnded', this.playerEnd, false);
      document.addEventListener('jeepCapVideoPlayerExit', this.playerExit, false);
    },

    async removeListeners(): Promise<void> {
      document.removeEventListener('jeepCapVideoPlayerPlay', this.playerPlay, false);
      document.removeEventListener('jeepCapVideoPlayerPause', this.playerPause, false);
      document.removeEventListener('jeepCapVideoPlayerEnded', this.playerEnd, false);
      document.removeEventListener('jeepCapVideoPlayerExit', this.playerExit, false);
    },

    async playerPlay(data: any): Promise<void> {
      console.log(`Event jeepCapVideoPlayerPlay ${data}`);
      return;
    },

    async playerPause(data: any): Promise<void> {
      console.log(`Event jeepCapVideoPlayerPause ${data}`);
      return;
    },

    async playerEnd(data: any): Promise<void> {
      console.log(`Event jeepCapVideoPlayerEnded ${data}`);
      await this.leavePlayer();
      return;
    },

    async playerExit(data: any): Promise<void> {
      console.log(`Event jeepCapVideoPlayerExit ${data}`);
      await this.leavePlayer();
      return;
    },

    async leavePlayer(): Promise<void> {
      this.removeListeners();
      try{
        await this.videoPlayer.stopAllPlayers();
      }
      catch(err){
        console.log(err);
      }
    },`

Any ideas what we need to do to get this working on Android?

**Comment by jepiqueau** [comment]
@jake-newsom thanks for using the plugin. can you share your app or a repro-app on github. Are you using Ionic/Vue or a pure vue3 js ?

**Comment by jepiqueau** [comment]
@jake-newsom i built up an app see [vite-vue-videoplayer-app](https://github.com/jepiqueau/vite-vue-videoplayer-app) it should help you

**Comment by jake-newsom** [comment]
@jepiqueau I can give this gist but can't provide the full repo. 

https://gist.github.com/jake-newsom/74125ffba80142b3dfda66289b200b4e

This is Ionic Vue, using capacitor 3

**Comment by jepiqueau** [comment]
@jake-newsom look at [vue-videoplayer-app-starter](https://github.com/jepiqueau/vue-videoplayer-app-starter) i think this works except the video subtitle i will check this tomorrow. For my knowledge it would be nice to share your apiService as i do not know how to use the inject. Hope this will help to make your development

**Comment by jepiqueau** [comment]
@jake-newsom i have fixed the issue with video subtitle in [vue-videoplayer-app-starter](https://github.com/jepiqueau/vue-videoplayer-app-starter) v0.0.2

**Comment by jake-newsom** [comment]
@jepiqueau Thanks for the info! Just to make sure I'm understanding, after looking through that project it seems the premise is to just have a page in our router that has nothing in it other than the Fullscreen Player... From another page, you'd tap the watch video button which navigates to this video player page providing the URL as a prop. 

Then within that page, you catch the exit event and theoretically would just do like router.back() or something to return to the previous page?

**Comment by jepiqueau** [comment]
@jake-newsom Yes you right, instead of a page you can also use a ion-modal and dismiss the modal on the exit event. voilà. So i close the issue. Feel free to re-open it if necessary. good luck with your app

**Comment by jake-newsom** [comment]
Hey @jepiqueau, still encountering issues unfortunately. We don't want to utilize PictureInPicture. If I disable that in the AndroidManifest then the app crashes when I press the back button on Android 11 while watching a video in full screen. 

I made a fork of the example you provided and tweaked that manifest file. 
https://github.com/jake-newsom/vue-videoplayer-app-starter

Is there no way to disable the picture in picture option?
